#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

mount_command="rclone mount ${RCLONE_REMOTE_PATH} ${rclone_mountpoint} $(echo $rclone_mount_basic_opts) $RCLONE_MOUNT_USER_OPTS"
echo "*** mounting => $mount_command"
exec s6-notifyoncheck -d -s 3000 \
    s6-setuidgid abc $mount_command
