#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

s6-svwait -U /var/run/service/mount

if [[ -n "${COPY_LOCAL_CRON:-}" ]]; then
    echo "*** scheduling job: copy_local"
    go-cron "$COPY_LOCAL_CRON" /usr/local/bin/copy_local &
    sleep 2
fi

if [[ -n "${MOVE_LOCAL_CRON:-}" ]]; then
    echo "*** scheduling job: move_local"
    go-cron "$MOVE_LOCAL_CRON" /usr/local/bin/move_local &
    sleep 2
fi

# any ENVs starting with RCLONE_REFRESH_CRON
while IFS='=' read -r name value; do
    [[ "$name" =~ ^RCLONE_REFRESH_CRON(_[0-9]+)?(_[A-Za-z0-9]+)?$ ]] || continue
    remote_num="${BASH_REMATCH[1]}"
    job_name="${BASH_REMATCH[2]}"

    dirs_var="RCLONE_REFRESH_DIRS${remote_num}${job_name}"
    remote_key="RCLONE_REMOTE_PATH${remote_num}"
    
    if [[ -n "$value" ]] && [[ -n "${!dirs_var:-}" ]] && [[ -n "${RCLONE_PATHS[$remote_key]:-}" ]]; then
        
        rc_path_value="${RCLONE_PATHS[$remote_key]}"
        opts="${rc_path_value##*|}"
        
        rc_port=$(echo "$opts" | grep -oP '\-\-rc\-addr=:\K[0-9]+' || true)
        
        if [[ -z "$rc_port" ]]; then
            echo "!!! ERROR: Skipping cron for remote $remote_key. Missing --rc-addr=:PORT in options."
            continue
        fi
        
        echo "*** scheduling job: vfs/refresh [${job_name}] for '${!dirs_var}' on RC port $rc_port"
        
        go-cron "$value" /usr/local/bin/rclone_refresh "${!dirs_var}" "$rc_port" &
        sleep 2
    fi
done < <(printenv)

exec wait
