#!/usr/bin/with-contenv bash
. /usr/local/bin/variables
set -eo pipefail

for key in $(printf '%s\n' "${!RCLONE_PATHS[@]}" | sort -t_ -k4n); do
    value="${RCLONE_PATHS[$key]}"
    mountpoint="${value#*|}"; mountpoint="${mountpoint%%|*}"
    if ! findmnt "$mountpoint" | grep -q fuse.rclone; then
        exit 1
    fi
done

trap run_exit_commands EXIT
trap 'run_commands "${POST_COMMANDS_FAILURE:-}"; exit 1' ERR

# post-check
if [[ -n "${RCLONE_REFRESH_ON_MOUNT:-}" ]]; then
    sleep 5
    rclone_refresh "$RCLONE_REFRESH_ON_MOUNT"
fi

if [ "$POOLING_FS" = "mergerfs" ]; then
    IFS=" " read -r -a mfs_user_opts <<< "$MFS_USER_OPTS"
    mount_command="mergerfs ${MFS_BRANCHES} /data -o ${mfs_basic_opts} -o ${mfs_user_opts}"
elif [ "$POOLING_FS" = "unionfs" ]; then
    IFS=" " read -r -a ufs_user_opts <<< "$UFS_USER_OPTS"
    mount_command="unionfs ${UFS_BRANCHES} /data -o ${ufs_basic_opts} -o ${ufs_user_opts}"
fi

if [ -n "$mount_command" ]; then
    echo "*** pooling => $mount_command"
    $mount_command
fi

trap - ERR
run_commands "${POST_COMMANDS_SUCCESS:-}"

exit 0
