#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

if ! findmnt $rclone_mountpoint | grep -q fuse.rclone; then
    exit 1
fi

# post-check
if [[ -n "${RCLONE_REFRESH_ON_MOUNT:-}" ]]; then
    sleep 5
    rclone_refresh "$RCLONE_REFRESH_ON_MOUNT"
fi

if [ "$POOLING_FS" = "mergerfs" ]; then
    IFS=" " read -r -a mfs_user_opts <<< "$MFS_USER_OPTS"

    mount_command="mergerfs ${mfs_branches} /data -o ${mfs_basic_opts} -o ${mfs_user_opts}"
    echo "*** pooling => $mount_command"
    exec $mount_command
fi

if [ "$POOLING_FS" = "unionfs" ]; then
    IFS=" " read -r -a ufs_user_opts <<< "$UFS_USER_OPTS"

    mount_command="unionfs ${ufs_branches} /data -o ${ufs_basic_opts} -o ${ufs_user_opts}"
    echo "*** pooling => $mount_command"
    exec $mount_command
fi

exit 0
