#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

if [ "$poolingfs" == "mergerfs" ]; then
    if [ $(findmnt ${fuse_mountpoint} | grep fuse.mergerfs | wc -l) -ne 1 ]; then
        exit 1
    fi
fi

if [ "$poolingfs" == "unionfs" ]; then
    if [ $(findmnt ${fuse_mountpoint} | grep fuse.unionfs | wc -l) -ne 1 ]; then
        exit 1
    fi
fi

exit 0
