#!/usr/bin/with-contenv bash

if [ "$(printenv POOLING_FS | tr -d '"' | tr -d "'")" == "mergerfs" ] && mountpoint -q /local; then

    sleep 5

    while [ -z "$(findmnt /cloud | grep fuse.rclone)" ]; do 
        echo "Waiting for rclone mount at /cloud. Retrying in 30s ..."
        sleep 30
    done

    # Mount if not already mounted
    if [ $(findmnt /data | grep fuse.mergerfs | wc -l) == "0" ]; then
        mfs_basic_opts="-o uid=${PUID:-911},gid=${PGID:-911},umask=022,allow_other"
        IFS=" " read -r -a mfs_user_opts <<< "$MFS_USER_OPTS"
        mfs_branches="/local=RW:/cloud=NC"

        mount_command="mergerfs ${mfs_basic_opts} -o ${mfs_user_opts} ${mfs_branches} /data"
        echo "executing => $mount_command"
        exec $mount_command
    fi
fi
