#!/usr/bin/with-contenv bash

if [ "$(printenv POOLING_FS | tr -d '"' | tr -d "'")" == "unionfs" ] && mountpoint -q /local; then

    sleep 5

    while [ -z "$(findmnt /cloud | grep fuse.rclone)" ]; do 
        echo "Waiting for rclone mount at /cloud. Retrying in 30s ..."
        sleep 30
    done

    # Mount if not already mounted
    if [ $(findmnt /data | grep fuse.unionfs | wc -l) == "0" ]; then
        ufs_basic_opts="-o uid=${PUID:-911},gid=${PGID:-911},umask=022,allow_other"
        IFS=" " read -r -a ufs_user_opts <<< "$UFS_USER_OPTS"
        ufs_branches="/local=RW:/cloud=RO"

        mount_command="unionfs ${ufs_basic_opts} -o ${ufs_user_opts} ${ufs_branches} /data"
        echo "executing => $mount_command"
        exec $mount_command
    fi
fi
